language: c
os:
  - linux
  - osx
before_install: |
  case $TRAVIS_OS_NAME in
    linux)
      curl http://dist.crystal-lang.org/apt/setup.sh | sudo bash
      sudo apt-get -q update
      ;;

    osx)
      brew update
      brew tap manastech/crystal
      ;;
  esac
install: |
  case $TRAVIS_OS_NAME in
    linux)
      sudo apt-get install libgmp3-dev crystal
      sudo sed -i -e 's/.*LIBRARY_PATH.*/export LIBRARY_PATH=\"$INSTALL_DIR\/embedded\/lib${LIBRARY_PATH:\+:$LIBRARY_PATH}\"/' /opt/crystal/bin/crystal
      curl "http://crystal-lang.s3.amazonaws.com/llvm/llvm-3.5.0-1-linux-x86_64.tar.gz" | tar xz -C /tmp
      curl "http://crystal-lang.s3.amazonaws.com/pcl/libpcl-1.12-1-linux-x86_64.tar.gz" | tar xz -C /tmp
      export LIBRARY_PATH=/tmp/libpcl-1.12-1/lib
      ;;

    osx)
      brew install gmp libevent crystal
      curl "http://crystal-lang.s3.amazonaws.com/llvm/llvm-3.5.0-1-darwin-x86_64.tar.gz" | tar xz -C /tmp
      ;;
  esac
  export PATH=/tmp/llvm-3.5.0-1/bin:$PATH
  export CRYSTAL_CONFIG_VERSION=ci
script:
  - make crystal spec
  # - bin/crystal evented_spec/*_spec.cr -Devented
notifications:
  irc:
    channels:
      - "irc.freenode.net#crystal-lang"
    use_notice: true
    skip_join: true
  slack:
    secure: Ng3nTqGWY+9p1pS6yjGqDhmRvdgbIZgTNpMWbO/ngwpCyicmD3jafZkShqqXbULZTJJr3OxIGzi6GHGusT0Ic/Pi9JCM3X3v/xuBruKIR+EnNyPo7IL4ZYAlwnXyJHlCHHDBq0gSHGvGJwsXn6IgZBPRfeIq+CCyQHVPyvc9EHE=
branches:
  only:
    - master
    - evented
