name: Forward Compatibility

on:
  push:
    paths:
      - .github/workflows/forward-compatibility.yml
  schedule:
  - cron: '0 3 * * *'
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  TRAVIS_OS_NAME: linux
  SPEC_SPLIT_DOTS: 160

jobs:
  # Test against *each* supported Crystal version for forward compatibility.
  #
  # This workflow runs on a nightly schedule on `master`.
  # It can also be dispatched manually when necessary.
  #
  # We run a basic version of this test on every commit which covers only the earliest and latest supported versions in `linux.yml#x86_64-gnu-test`.
  x86_64-gnu-test-forward_compatibility:
    env:
      ARCH: x86_64
      ARCH_CMD: linux64
      CRYSTAL_BOOTSTRAP_VERSION: ${{ matrix.crystal_bootstrap_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        crystal_bootstrap_version: [1.7.3, 1.8.2, 1.9.2, 1.10.1, 1.11.2, 1.12.2, 1.13.3, 1.14.1, 1.15.1, 1.16.3, 1.17.1]
        env: [{}]
        include:
          # libffi is only available starting from the 1.2.2 build images
          # pcre2 is only available starting from the 1.7.0 build images
          - crystal_bootstrap_version: 1.1.1
            env:
              FLAGS: -Dwithout_ffi
              USE_PCRE1: true
          - crystal_bootstrap_version: 1.2.2
            env:
              USE_PCRE1: true
          - crystal_bootstrap_version: 1.3.2
            env:
              USE_PCRE1: true
          - crystal_bootstrap_version: 1.4.1
            env:
              USE_PCRE1: true
          - crystal_bootstrap_version: 1.5.1
            env:
              USE_PCRE1: true
          - crystal_bootstrap_version: 1.6.2
            env:
              USE_PCRE1: true
    steps:
      - name: Download Crystal source
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Prepare System
        run: bin/ci prepare_system

      - name: Prepare Build
        run: bin/ci prepare_build

      - name: Test
        run: bin/ci build
        env: ${{ matrix.env }}
