name: Lint
on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: cachix/install-nix-action@fd24c48048070c1be9acd18c9d369a83f0fe94d7 # v31
      - uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - run: git fetch origin "${TARGET_BRANCH}"
      - name: Run pre-commit hooks for changes against target branch (${TARGET_BRANCH})
        run: pre-commit run --from-ref "origin/${TARGET_BRANCH}" --to-ref HEAD
        shell: devenv shell -c -- bash -e {0}
        if: "${{ github.event_name != 'workflow_dispatch' }}"
      - name: Run pre-commit on all files
        run: pre-commit run --all-files
        shell: devenv shell -c -- bash -e {0}
        if: "${{ github.event_name == 'workflow_dispatch' }}"
    env:
      TARGET_BRANCH: "${{ github.base_ref || 'master' }}"
