name: Regex Engine CI

on: [push, pull_request]

jobs:
  pcre:
    runs-on: ubuntu-latest
    name: "PCRE"
    container: crystallang/crystal:1.7.2-alpine
    steps:
      - name: Download Crystal source
        uses: actions/checkout@v3
      - name: Assert using PCRE
        run: bin/crystal eval 'abort unless Regex::Engine == Regex::PCRE'
      - name: Run Regex specs
        run: bin/crystal spec --order=random spec/std/regex*
  pcre2:
    runs-on: ubuntu-latest
    name: "PCRE2"
    container: crystallang/crystal:1.7.2-alpine
    steps:
      - name: Download Crystal source
        uses: actions/checkout@v3
      - name: Install PCRE2
        run: apk add pcre2-dev
      - name: Assert using PCRE2
        run: bin/crystal eval 'abort unless Regex::Engine == Regex::PCRE2'
      - name: Assert select PCRE
        run: bin/crystal eval -Duse_pcre 'abort unless Regex::Engine == Regex::PCRE'
      - name: Run Regex specs
        run: bin/crystal spec --order=random spec/std/regex*
