name: WebAssembly CI

on: [push, pull_request]

env:
  SPEC_SPLIT_DOTS: 160

jobs:
  wasm32-test:
    runs-on: ubuntu-latest
    container: crystallang/crystal:1.6.1-build
    steps:
      - name: Download Crystal source
        uses: actions/checkout@v2

      - name: Install wasmtime
        run: |
          apt-get update
          apt-get install -y curl
          touch ~/.bashrc
          curl https://wasmtime.dev/install.sh -sSf | bash -s - --version v1.0.1

      - name: Add wasm-ld symlink
        run: |
          ln -s $(which wasm-ld-15 || which wasm-ld-14 || which wasm-ld-13 || which wasm-ld-12 || which wasm-ld-11 || which wasm-ld-10) /usr/bin/wasm-ld

      - name: Download wasm32 libs
        run: |
          mkdir wasm32-wasi-libs
          curl -LO https://github.com/lbguilherme/wasm-libs/releases/download/0.0.2/wasm32-wasi-libs.tar.gz
          echo "114dd08b776c92e15b4ec83178fa486dc436e24b7f662c3241a8cdf2506fe426  wasm32-wasi-libs.tar.gz" | sha256sum -c -
          tar -f wasm32-wasi-libs.tar.gz -C wasm32-wasi-libs -xz
          rm wasm32-wasi-libs.tar.gz

      - name: Build spec/wasm32_std_spec.cr
        run: bin/crystal build spec/wasm32_std_spec.cr -o wasm32_std_spec.wasm --target wasm32-wasi
        env:
          CRYSTAL_LIBRARY_PATH: ${{ github.workspace }}/wasm32-wasi-libs

      - name: Run wasm32_std_spec.wasm
        run: |
          . ~/.bashrc
          wasmtime run wasm32_std_spec.wasm
